In [1]:
from keras.models import load_model
model = load_model("./Model1_30X30_4_8.h5")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import tensorflow as tf
from PIL import Image
import os
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from imutils import paths
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout 

In [3]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 28, 28, 32)        896       
                                                                 
 conv2d_5 (Conv2D)           (None, 26, 26, 32)        9248      
                                                                 
 conv2d_6 (Conv2D)           (None, 24, 24, 32)        9248      
                                                                 
 conv2d_7 (Conv2D)           (None, 22, 22, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 11, 11, 32)       0         
 2D)                                                             
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 5, 5, 32)         0         
 2D)                                                  

In [4]:
# Classes of trafic signs
classes = { 0:'Speed limit (20km/h)',
            1:'Speed limit (30km/h)',
            2:'Speed limit (50km/h)',
            3:'Speed limit (60km/h)',
            4:'Speed limit (70km/h)',
            5:'Speed limit (80km/h)',
            6:'End of speed limit (80km/h)',
            7:'Speed limit (100km/h)',
            8:'Speed limit (120km/h)',
            9:'No passing',
            10:'No passing veh over 3.5 tons',
            11:'Right-of-way at intersection',
            12:'Priority road',
            13:'Yield',
            14:'Stop',
            15:'No vehicles',
            16:'Vehicle > 3.5 tons prohibited',
            17:'No entry',
            18:'General caution',
            19:'Dangerous curve left',
            20:'Dangerous curve right',
            21:'Double curve',
            22:'Bumpy road',
            23:'Slippery road',
            24:'Road narrows on the right',
            25:'Road work',
            26:'Traffic signals',
            27:'Pedestrians',
            28:'Children crossing',
            29:'Bicycles crossing',
            30:'Beware of ice/snow',
            31:'Wild animals crossing',
            32:'End speed + passing limits',
            33:'Turn right ahead',
            34:'Turn left ahead',
            35:'Ahead only',
            36:'Go straight or right',
            37:'Go straight or left',
            38:'Keep right',
            39:'Keep left',
            40:'Roundabout mandatory',
            41:'End of no passing',
            42:'End no passing vehicle > 3.5 tons' }

In [6]:
csv = pd.read_csv("./Test.csv")

label = csv["ClassId"].values
imgs = csv["Path"].values
data = []

# print(label)
print(imgs)

count = 0
for img in imgs:
    image = Image.open(img)
    image = image.resize((30,30))
    data.append(np.array(image))
    count+=1

X_test = np.array(data)
print(count)
print(X_test)

['Test/00000.png' 'Test/00001.png' 'Test/00002.png' ... 'Test/12627.png'
 'Test/12628.png' 'Test/12629.png']
12630
[[[[116 140 175]
   [116 138 171]
   [119 138 173]
   ...
   [102 119 150]
   [101 122 149]
   [ 93 112 139]]

  [[116 142 177]
   [116 141 175]
   [117 141 174]
   ...
   [120 143 178]
   [122 144 176]
   [122 142 174]]

  [[118 142 174]
   [116 141 175]
   [114 140 172]
   ...
   [121 144 181]
   [122 144 180]
   [119 142 178]]

  ...

  [[117 137 168]
   [115 135 165]
   [116 135 164]
   ...
   [116 138 170]
   [116 136 168]
   [118 139 171]]

  [[116 136 166]
   [115 134 167]
   [115 133 165]
   ...
   [114 135 168]
   [116 136 166]
   [115 139 167]]

  [[112 135 166]
   [111 134 165]
   [119 135 166]
   ...
   [115 137 166]
   [117 138 167]
   [114 140 170]]]


 [[[ 62  72  61]
   [ 89  81  63]
   [ 94  82  65]
   ...
   [ 78  64  68]
   [ 72  65  67]
   [ 74  68  68]]

  [[ 64  72  60]
   [ 97  83  65]
   [ 97  81  63]
   ...
   [ 75  63  65]
   [ 93  69  71]
   [ 88

In [7]:
Y_Prediction = model.predict(x = X_test, steps=len(X_test), verbose = 1)
np.round(Y_Prediction)
print(Y_Prediction)

12630/12630 [==============================] - ETA:  - 129s 10ms/step
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 3.42068442e-13 1.31325824e-05 ... 6.27397370e-17
  3.58350665e-13 1.84651753e-06]
 [0.00000000e+00 9.97591995e-16 5.47817119e-15 ... 5.12246351e-17
  1.10147274e-32 9.01909168e-17]
 [0.00000000e+00 3.22714640e-34 8.55054776e-24 ... 4.23818127e-29
  0.00000000e+00 4.45590941e-32]]


In [8]:
predicted_classes = []
for i in range(len(Y_Prediction)):
    predicted_classes.append(np.argmax(Y_Prediction[i]))

predicted_classes = np.array(predicted_classes)
print(predicted_classes)
print(label)

[16  1 38 ...  6  7 10]
[16  1 38 ...  6  7 10]


In [9]:
from sklearn.metrics import accuracy_score
print(accuracy_score(label, predicted_classes))

0.9527315914489312
